In [1]:
import numpy as np

In [2]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [4]:
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [5]:
arr.transpose((0,1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr.transpose(1,0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [7]:
help(arr.swapaxes)

Help on built-in function swapaxes:

swapaxes(...) method of numpy.ndarray instance
    a.swapaxes(axis1, axis2)
    
    Return a view of the array with `axis1` and `axis2` interchanged.
    
    Refer to `numpy.swapaxes` for full documentation.
    
    See Also
    --------
    numpy.swapaxes : equivalent function



In [8]:
help(numpy.swapaxes)

NameError: name 'numpy' is not defined

In [9]:
help(np.swapaxes)

Help on function swapaxes in module numpy.core.fromnumeric:

swapaxes(a, axis1, axis2)
    Interchange two axes of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis1 : int
        First axis.
    axis2 : int
        Second axis.
    
    Returns
    -------
    a_swapped : ndarray
        For Numpy >= 1.10, if `a` is an ndarray, then a view of `a` is
        returned; otherwise a new array is created. For earlier Numpy
        versions a view of `a` is returned only if the order of the
        axes is changed, otherwise the input array is returned.
    
    Examples
    --------
    >>> x = np.array([[1,2,3]])
    >>> np.swapaxes(x,0,1)
    array([[1],
           [2],
           [3]])
    
    >>> x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
    >>> x
    array([[[0, 1],
            [2, 3]],
           [[4, 5],
            [6, 7]]])
    
    >>> np.swapaxes(x,0,2)
    array([[[0, 4],
            [2, 6]],
           [[1, 5],
            [3, 7]]

In [10]:
np.dot(arr.T, arr)

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [11]:
help(arr.dot)

Help on built-in function dot:

dot(...) method of numpy.ndarray instance
    a.dot(b, out=None)
    
    Dot product of two arrays.
    
    Refer to `numpy.dot` for full documentation.
    
    See Also
    --------
    numpy.dot : equivalent function
    
    Examples
    --------
    >>> a = np.eye(2)
    >>> b = np.ones((2, 2)) * 2
    >>> a.dot(b)
    array([[ 2.,  2.],
           [ 2.,  2.]])
    
    This array method can be conveniently chained:
    
    >>> a.dot(b).dot(b)
    array([[ 8.,  8.],
           [ 8.,  8.]])



In [13]:
arr.dot(arr.T)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [17]:
arr3d = np.arange(12).reshape((3,2,2))
arr3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [16]:
arr3d.transpose((0,2,1))

array([[[ 0,  2],
        [ 1,  3]],

       [[ 4,  6],
        [ 5,  7]],

       [[ 8, 10],
        [ 9, 11]]])