In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [8]:
np.save('my_array.npy', arr)

In [4]:
arr = 'hogehoge'
arr

'hogehoge'

In [7]:
arr = np.load('my_array.npy')
arr

array([0, 1, 2, 3, 4])

In [9]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.savez('my_archive.npz', x=arr, y=arr2)

In [17]:
arr3 = np.load('my_archive.npz')

In [18]:
arr3['x']

array([0, 1, 2, 3, 4])

In [19]:
arr3['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr3

In [39]:
arr = np.array([[1,2,3,4],[5,6,7,8]], dtype=int)
np.savetxt('my_array.txt', arr, delimiter=',')

In [40]:
!cat my_array.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00


In [38]:
np.loadtxt('my_array.txt', delimiter=',')

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.]])