In [1]:
import numpy as np
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [3]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [4]:
A = np.random.randn(10)
A

array([ 0.85067361,  0.32261779,  0.13104093,  1.23532477,  0.29425762,
        1.35425409, -0.65793549,  0.3041435 , -0.63434388,  0.37082066])

In [5]:
B = np.random.randn(10); B

array([ 0.28205358,  0.70471448,  0.43371685,  1.48456318,  2.12522164,
       -0.0670759 ,  2.76711403,  0.25644506,  1.07353613, -0.46933124])

In [6]:
A + B

array([ 1.13272719,  1.02733226,  0.56475777,  2.71988795,  2.41947926,
        1.28717819,  2.10917854,  0.56058857,  0.43919225, -0.09851058])

In [7]:
np.add(A, B)

array([ 1.13272719,  1.02733226,  0.56475777,  2.71988795,  2.41947926,
        1.28717819,  2.10917854,  0.56058857,  0.43919225, -0.09851058])